### ISSUE TITLE
IMDbWordEmbeddingDemo.py not working

### ISSUE THREAD

**Issue by olegranmo** [cair/tmu#53]
python3 ./examples/autoencoder/IMDbWordEmbeddingDemo.py
Could not import pycuda: No module named 'pycuda'
No module named 'pycuda'
Traceback (most recent call last):
  File "/Users/oleg/Dropbox/Research/Implementations/tmp/tmu/tmu/clause_bank/clause_bank_cuda.py", line 41, in <module>
    from pycuda._driver import Device, Context
ModuleNotFoundError: No module named 'pycuda'
Could not import pycuda. This indicates that it is not installed! A possible fix is to run 'pip install pycuda'. Fallback to CPU ClauseBanks.
Hash mismatch, redownloading file
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.64M/1.64M [00:00<00:00, 6.54MiB/s]
Traceback (most recent call last):
  File "/Users/oleg/Dropbox/Research/Implementations/tmp/tmu/./examples/autoencoder/IMDbWordEmbeddingDemo.py", line 194, in <module>
    main()
  File "/Users/oleg/Dropbox/Research/Implementations/tmp/tmu/./examples/autoencoder/IMDbWordEmbeddingDemo.py", line 72, in main
    word_to_id = dataloader.get_word_index()
  File "/Users/oleg/Dropbox/Research/Implementations/tmp/tmu/tmu/data/imdb_keras.py", line 149, in get_word_index
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/oleg/.cache/tmu/datasets/imdb_word_index'

**Comment by perara** [comment]
This I think is fixed. please reopen if its still an issue.
